create table "public"."interview_feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "confidence" smallint,
    "communication" smallint,
    "goodPoints" character varying[],
    "badPoints" character varying
);


alter table "public"."interview_transcript" add column "isInterviewer" boolean;

CREATE UNIQUE INDEX interview_feedback_pkey ON public.interview_feedback USING btree (id, created_at);

alter table "public"."interview_feedback" add constraint "interview_feedback_pkey" PRIMARY KEY using index "interview_feedback_pkey";


