create table "public"."interview" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "companyName" character varying not null,
    "minExpectedMonthlyIncome" bigint not null,
    "maxExpectedMonthlyIncome" bigint not null,
    "userId" uuid not null
);


create table "public"."interview_message" (
    "id" bigint generated by default as identity not null,
    "interviewId" bigint not null,
    "createdAt" timestamp with time zone not null default now(),
    "message" character varying not null,
    "isUser" boolean not null
);

CREATE UNIQUE INDEX interview_message_pkey ON public.interview_message USING btree (id);

CREATE UNIQUE INDEX interview_pkey ON public.interview USING btree (id);

alter table "public"."interview" add constraint "interview_pkey" PRIMARY KEY using index "interview_pkey";

alter table "public"."interview_message" add constraint "interview_message_pkey" PRIMARY KEY using index "interview_message_pkey";

alter table "public"."interview" add constraint "interview_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."interview" validate constraint "interview_userId_fkey";

alter table "public"."interview_message" add constraint "interview_message_interviewId_fkey" FOREIGN KEY ("interviewId") REFERENCES interview(id) not valid;

alter table "public"."interview_message" validate constraint "interview_message_interviewId_fkey";
