create table "public"."user" (
    "id" bigint generated by default as identity not null,
    "firstName" character varying not null,
    "lastName" character varying not null,
    "createdAt" timestamp with time zone default now(),
    "userId" uuid not null,
    "yearsOfExperience" bigint,
    "currentMonthlyIncome" bigint,
    "minExpectedMonthlyIncome" bigint,
    "maxExpectedMonthlyIncome" bigint
);


CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

CREATE UNIQUE INDEX "user_userId_key" ON public."user" USING btree ("userId");

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."user" add constraint "user_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."user" validate constraint "user_userId_fkey";

alter table "public"."user" add constraint "user_userId_key" UNIQUE using index "user_userId_key";


