create table "public"."interview" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "companyName" character varying,
    "role" character varying,
    "minExpectedComp" integer,
    "maxExpectedComp" integer
);


CREATE UNIQUE INDEX interview_pkey ON public.interview USING btree (id);

alter table "public"."interview" add constraint "interview_pkey" PRIMARY KEY using index "interview_pkey";


