create table "public"."interview_transcript" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "transcript" character varying
);


CREATE UNIQUE INDEX interview_transcript_pkey ON public.interview_transcript USING btree (id, created_at);

alter table "public"."interview_transcript" add constraint "interview_transcript_pkey" PRIMARY KEY using index "interview_transcript_pkey";


